/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppTendersIndexRouteImport } from './routes/_app.tenders.index'
import { Route as AppTendersTenderIdRouteImport } from './routes/_app.tenders.$tenderId'
import { Route as AppTendersNewRouteImport } from './routes/_app.tenders.new'
import { Route as AppTendersTenderIdEditRouteImport } from './routes/_app.tenders.$tenderId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppTendersIndexRoute = AppTendersIndexRouteImport.update({
  id: '/tenders/',
  path: '/tenders/',
  getParentRoute: () => AppRoute,
} as any)
const AppTendersTenderIdRoute = AppTendersTenderIdRouteImport.update({
  id: '/tenders/$tenderId',
  path: '/tenders/$tenderId',
  getParentRoute: () => AppRoute,
} as any)
const AppTendersNewRoute = AppTendersNewRouteImport.update({
  id: '/tenders/new',
  path: '/tenders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTendersTenderIdEditRoute = AppTendersTenderIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppTendersTenderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/tenders/$tenderId': typeof AppTendersTenderIdRouteWithChildren
  '/tenders/new': typeof AppTendersNewRoute
  '/tenders/': typeof AppTendersIndexRoute
  '/tenders/$tenderId/edit': typeof AppTendersTenderIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/tenders/$tenderId': typeof AppTendersTenderIdRouteWithChildren
  '/tenders/new': typeof AppTendersNewRoute
  '/tenders': typeof AppTendersIndexRoute
  '/tenders/$tenderId/edit': typeof AppTendersTenderIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/tenders/$tenderId': typeof AppTendersTenderIdRouteWithChildren
  '/_app/tenders/new': typeof AppTendersNewRoute
  '/_app/tenders/': typeof AppTendersIndexRoute
  '/_app/tenders/$tenderId/edit': typeof AppTendersTenderIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/tenders/$tenderId'
    | '/tenders/new'
    | '/tenders/'
    | '/tenders/$tenderId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/tenders/$tenderId'
    | '/tenders/new'
    | '/tenders'
    | '/tenders/$tenderId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/tenders/$tenderId'
    | '/_app/tenders/new'
    | '/_app/tenders/'
    | '/_app/tenders/$tenderId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenders/': {
      id: '/_app/tenders/'
      path: '/tenders'
      fullPath: '/tenders/'
      preLoaderRoute: typeof AppTendersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenders/$tenderId': {
      id: '/_app/tenders/$tenderId'
      path: '/tenders/$tenderId'
      fullPath: '/tenders/$tenderId'
      preLoaderRoute: typeof AppTendersTenderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenders/new': {
      id: '/_app/tenders/new'
      path: '/tenders/new'
      fullPath: '/tenders/new'
      preLoaderRoute: typeof AppTendersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenders/$tenderId/edit': {
      id: '/_app/tenders/$tenderId/edit'
      path: '/edit'
      fullPath: '/tenders/$tenderId/edit'
      preLoaderRoute: typeof AppTendersTenderIdEditRouteImport
      parentRoute: typeof AppTendersTenderIdRoute
    }
  }
}

interface AppTendersTenderIdRouteChildren {
  AppTendersTenderIdEditRoute: typeof AppTendersTenderIdEditRoute
}

const AppTendersTenderIdRouteChildren: AppTendersTenderIdRouteChildren = {
  AppTendersTenderIdEditRoute: AppTendersTenderIdEditRoute,
}

const AppTendersTenderIdRouteWithChildren =
  AppTendersTenderIdRoute._addFileChildren(AppTendersTenderIdRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTendersTenderIdRoute: typeof AppTendersTenderIdRouteWithChildren
  AppTendersNewRoute: typeof AppTendersNewRoute
  AppTendersIndexRoute: typeof AppTendersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppTendersTenderIdRoute: AppTendersTenderIdRouteWithChildren,
  AppTendersNewRoute: AppTendersNewRoute,
  AppTendersIndexRoute: AppTendersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
